allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
    project.pluginManager.withPlugin("com.android.library") {
        if (project.name == 'better_player') {
            project.android.namespace = 'com.jhomlala.better_player'
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
